name: Node.js Test and Deploy Pipline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-Latest

    steps:
      - name: copy code into the runner machine
        uses: actions/checkout@v4

      - name: set up Node.js runtime enviroment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: run our test script 
        run: node app.js
  
  deploy-app:
    runs-on: ubuntu-Latest
    needs: run-tests
    
    steps:
      - name: Simulate production Deployment 
        run: |
          echo "Connecting to production servers..."
          echo "Deploying the latest updates successfully!"